/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();
  static const _kFontFam = 'IconFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData icon_add =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_search =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_more =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_text =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_question =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_delete =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_eyes_active =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_eyes_inactive =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_octagon =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_icon =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_copy =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_outline =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calling =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_upper_arrow =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_down_arrow =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_safe =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_right_arrow =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presention_chart =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_2user =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_2 =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2 =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal_star =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan_barcode =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dot =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paperclip =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData markasread =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_circle_outline =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teacher =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diagram =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_up =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_up =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_arrow_down_full =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_arrow_up_full =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
